language: python
python:
  - "2.7"
  - "3.4"

addons:
  postgresql: "9.4"

before_script:
  - psql -U postgres -c "create database sih_test;"
  - psql -U postgres -c "create extension postgis;" sih_test

install:
  - pip install -r requirements.txt

script: 
  - nosetests --with-coverage --cover-package sih sih
