language: python
python:
  - "2.7"
  - "3.4"

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.pip-cache
    - $HOME/.bower-cache

before_script:
  - psql -U postgres -c "create database sih_test;"
  - psql -U postgres -c "create extension postgis;" sih_test
  - bower install --config.storage.cache=$HOME/.bower-cache

install:
  - pip install -r requirements.txt --cache-dir $HOME/.pip-cache
  - npm install -g less requirejs bower

script: 
  - nosetests --with-coverage --cover-package sih sih
