---

- hosts: appservers
  roles:
    - { role: common, tags: [common] }
    - { role: nginx, tags: [nginx] }
    - { role: uwsgi, tags: [uwsgi] }

- hosts: dbservers
  roles:
   - { role: postgresql, tags: [postgresql] }
