---

- hosts: appservers
  roles:
    - { role: common, tags: [common] }
    - { role: app, tags: [app] }

- hosts: dbservers
  roles:
   - { role: postgresql, tags: [postgresql] }

- hosts: mapservers
  roles:
    - { role: common, tags: [common] }
    - { role: mapproxy, tags: [mapproxy] }
