---

- name: install nginx
  apt: pkg=nginx-extras state=present cache_valid_time=3600 update_cache=yes
  notify:
    - enable nginx

- name: install python-passlib
  apt: pkg=python-passlib state=present cache_valid_time=3600 update_cache=yes

- name: remove /etc/nginx/sites-{enabled,available}
  file: path={{ item }} state=absent
  with_items:
    - /etc/nginx/sites-enabled
    - /etc/nginx/sites-available

- name: create /etc/nginx/apps.d
  file: path=/etc/nginx/apps.d state=directory

- name: replace default nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: open http and https port
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - 80
    - 443

- name: ensure nginx is enabled and running
  service: name=nginx enabled=yes state=started
